### ISSUE TITLE
sub-domain boundary noise when mpirun using 4 cores

### ISSUE THREAD

**Issue by ZhouleiJoeStone** [IBirdSoft/openfpm_pdata_1.1.0#4]
Hi, all the developers of Openfpm:
First, thank you for your work in Openfpm. It's really helpful for me.
Now, I meet with some problem in my small test case, which is similar to [SPH with Dynamic load Balancing ](http://ppmcore.mpi-cbg.de/doxygen/openfpm_pdata/Vector_7_sph_dlb.html).
I add little code to calculate the surface tension of bubble in water. My code is OK in a single core. [Like Fig 1](https://github.com/ZhouleiJoeStone/Pictures/blob/master/SPH_single_core.png)

But, when I run it in 4 core, there is some noise force in sub-domain boundary. [Like Fig 2](https://github.com/ZhouleiJoeStone/Pictures/blob/master/SPH_4_cores.png)
As you can see, there is some noise( little Arrow) in sub-domain boundary.
From the picture, I think the magnitude of the boundary noise can't be ignored when I want to do micro-scale simulation.

I try to change the cellList radius in " auto NN = vd.getCellList(2*dx); ", but It doesn't work.
I'm concerned if Openfpm introduces the numerical errors when communicating between ghost layers??? 
I upload my test code in [here](https://github.com/ZhouleiJoeStone/Pictures).
I'd be truly grateful if someone can solve the problem.

**Comment by incardon** [comment]
Hi ZhouleiJoeStone

[diff.txt](https://github.com/IBirdSoft/openfpm_pdata_1.1.0/files/2861060/diff.txt)

I looked at your code. I attached a patch to fix your code. But is good to explain


Short story the fix is:

 template<typename Kernel, typename Vector, typename CellList>
 void computeGradientColorField(Kernel & kernel,Vector & vd,CellList & NN)
 {
    vd.template ghost_get<Color>(KEEP_PROPERTIES);


 template<typename Kernel, typename Vector, typename CellList>
 void computeSurfaceTensionForce(Kernel & kernel,Vector & vd,CellList & NN, Real sigma)
 {
    vd.template ghost_get<GradC2>(KEEP_PROPERTIES);

Long story: 

Every time we have to do a loop we have to me careful that if we read from the ghost/border the data is up to date. This can be done for sake of simplicity every time you have a loop that involve using Cell-list and neighborhood access you do 

vd.ghost_get<Type,Mass,Rho,Pressure,Velocity,Color,GradC2,GradC>();

computeColorField (Well here we can omit considering that we did it at the beginning of the program)
computeGradientColorField
computeSurfaceTensionForce

this will make your program work.

A second step is to optimize a little bit and instead of refresh all the properties (that mean communication for each of them) refresh only the one that we read in the loop. 

So for 
computeGradientColorField

 vd.template ghost_get<Mass,Rho,Color>(KEEP_PROPERTIES);

and for computeSurfaceTensionForce

vd.template ghost_get<Mass,Rho,GradC2>(KEEP_PROPERTIES);

KEEP_PROPERTIES is a flag necessary to lock the state of the other properties

Then we can further refine our optimization thinking that  

computeColorField only modify Color and the rest does not change so for the subsequent step
computeGradientColorField we just have to refresh Color that is actually used in this step
(vd.template ghost_get<Color>(KEEP_PROPERTIES)). Again same concept for next step for
computeSurfaceTensionForce it use Mass,Rho,GradC2 but only GradC2 must be refreshed because has been nodified in the previous step

Let me know if it is clear

**Comment by ZhouleiJoeStone** [comment]
@incardon Thank you for your patient explanation. It works. 
I find the official [example](http://ppmcore.mpi-cbg.de/doxygen/openfpm_pdata/Vector_1_ghost_get.html) in openfpm webpage, which teaches users how to use ghost_get and the KEEP_PROPERTIES Flag. It will be helpful for anyone may encounter a similar problem.
Thank you again, @incardon. It's so helpful

**Comment by ZhouleiJoeStone** [comment]
Can I understand that ghost_get is thread synchronization likes barrier in CUDA? no thread makes progress beyond this ghost_get point until all threads (cpus) have arrived at this synchronization point.

**Comment by incardon** [comment]
Yes, from a shared memory prospective like CUDA __syncthreads you can also see in this way. From a data distributed prospective and having multiple process, it is a barrier in the sense that it wait the neighborhood processes send the border data.

**Comment by incardon** [comment]
vd.updateCellList(NN) this does not produce CPU synchronization.

The other is ghost_put

**Comment by ZhouleiJoeStone** [comment]
@incardon Thank you. That's very nice of you.
